### ISSUE TITLE
Change anchor id format

### ISSUE THREAD

**Issue by m-mujica** [bit-docs/bit-docs-html-toc#4]
As of < v0.2.1 the generated ids look like `sig_{{ANCHOR-TEXT}}` we are going to change them to use the format `section_{{ANCHOR-TEXT}}` which is used by the current StealJS website.

See https://github.com/stealjs/stealjs/issues/5#issuecomment-258816385

**Comment by justinbmeyer** [comment]
Would this be good to work like Github?.  I've implemented how it converts headers here: https://github.com/bit-docs/bit-docs-generate-readme/blob/master/helpers.js#L4
